const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const http=require('node:http');const {chromium}=require('playwright');const {createServer,extractProduct}=require('../server.cjs');
const source='https://www.certina.com/be-fr/watch/ds-8-gent-40mm/c0454104404100';
(async()=>{
 const html=await fs.readFile(path.join(__dirname,'fixtures/certina-ds8.html'),'utf8'),proposal=extractProduct(html,source),specs=Object.fromEntries(proposal.specs.map(s=>[s.label,s.value]));
 assert.equal(proposal.name,'Certina DS-8 Gent 40mm');assert.equal(proposal.reference,'C045.410.44.041.00');assert.equal(proposal.photo,'https://www.certina.com/sites/default/files/maps-medias/C045.410.44.041.00_SLD.png');assert(!proposal.photo.includes('caseback'));
 assert.deepEqual(specs,{'Diamètre / largeur':'40.00mm','Épaisseur':'8.35mm','Corne à corne':'47.19mm','Entrecorne':'20.00mm','Boîtier':'Titane','Verre':'Traitement antireflet simple face · Verre saphir','Étanchéité':'Jusqu’à une pression de 10 bar (100 m)','Poids':'80.00g','Couleur du cadran':'Bleu','Énergie / mouvement':'Quartz','Calibre':'F05.412','Prix indicatif':'€ 590,00'});
 const normalize=s=>s.replace(/\s+/g,' ').trim();for(const s of proposal.specs)assert(normalize(proposal._text).includes(normalize(s.quote)),s.label+' quote must exist in the scoped source');
 assert(!proposal._text.includes('C045.010.55.031.00'));assert(!proposal._text.includes('variation de marche'));assert(proposal._text.includes('Precidrive™'));assert.equal(specs['Réserve de marche'],undefined);
 assert.equal(extractProduct('<title>No image</title>', 'https://example.org/watch').photo,'');
 assert.equal(extractProduct(html,'https://certina.com.evil.example/watch/c0454104404100').reference,'');
 assert.throws(()=>extractProduct(html,source.replace('c0454104404100','c0454104404101')),/référence affichée/);
 const withoutThickness=html.replace(/<div class="field field--name-field-watch-box-height[^]*?<\/div>\s*<\/div>/,'');assert(!extractProduct(withoutThickness,source).specs.some(s=>s.label==='Épaisseur'));
 const foreignLabels=html.replace('Diamètre de la boîte','Diameter').replace('Hauteur</div>','Height</div>').replace('Modèle</div>','Model</div>');assert.equal(extractProduct(foreignLabels,source).specs.find(s=>s.label==='Calibre').value,'F05.412');
 assert(!extractProduct('<p>Hauteur</p><p>42mm</p><p>Modèle</p><p>Unrelated</p>', 'https://example.org/watch').specs.some(s=>s.label==='Épaisseur'||s.label==='Calibre'));
 let calls=0;const provider=http.createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;calls++;assert(!body.includes('C045.010.55.031.00'));assert(!body.includes('variation de marche'));const ai={characteristics:[{label:'Verre',value:'Verre saphir avec antireflet simple face',quote:'Verre\nTraitement antireflet simple face\nVerre saphir'},{label:'Prix indicatif',value:'590 USD',quote:'€ 590,00'},{label:'Diamètre / largeur',value:'31.0mm',quote:'Quartz, ⌀ 31.0mm'}],roles:[]};res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(ai)}}]}));});await new Promise(r=>provider.listen(0,'127.0.0.1',r));
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'watch-certina-')),server=createServer({password:'certina-test',dataDir:dir,productDownloader:async url=>({html,url}),aiConfig:{endpoint:'http://127.0.0.1:'+provider.address().port+'/v1/chat/completions',model:'test-model'}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let browser;
 try{
  browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium'});const context=await browser.newContext();await context.route('https://**',r=>r.abort());const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const ready=p=>p.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('à jour'));
  async function login(p){await p.goto(base);await p.locator('[data-connect]').first().click();await p.locator('#sharedPassword').fill('certina-test');await p.locator('#loginButton').click();await ready(p);}
  const disk=async()=>JSON.parse(await fs.readFile(path.join(dir,'collection.json'),'utf8'));
  await login(page);const before=await disk();await page.locator('#add').click();await page.locator('#productUrl').fill(source);await page.locator('#analyzeURL').click();await page.locator('#applyProductProposal').waitFor();assert.equal(calls,0);assert.equal((await disk()).revision,before.revision);const preview=await page.locator('#productProposal').innerText();assert(preview.includes('47.19mm'));assert(preview.includes('F05.412'));assert(preview.includes('€ 590,00'));assert(!preview.includes('€ 540,00'));
  await page.locator('#applyProductProposal').click();assert.equal(await page.locator('#modelName').inputValue(),proposal.name);assert.equal(await page.locator('#photoUrl').inputValue(),proposal.photo);await page.locator('#editorNotes').fill('À essayer au poignet');await page.locator('#roles input[value="0"]').check();await page.locator('#watchForm [type="submit"]').click();await ready(page);const saved=(await disk()).collection.watches.at(-1);assert.equal(saved.specs['Référence'],proposal.reference);for(const[label,value]of Object.entries(specs))assert.equal(saved.specs[label],value);assert.equal(saved.notes,'À essayer au poignet');assert(saved.blocks.some(b=>b.text.includes('47.19mm')));
  const aiResponse=await context.request.post(base+'/api/product-preview',{data:{url:source,useAI:true}});assert.equal(aiResponse.status(),200);const enriched=await aiResponse.json();assert.equal(calls,1);assert.equal(enriched.ai.used,true);assert.equal(enriched.specs.find(s=>s.label==='Prix indicatif').value,'€ 590,00');assert.equal(enriched.specs.find(s=>s.label==='Diamètre / largeur').value,'40.00mm');assert.equal(enriched.reference,proposal.reference);
  const second=await browser.newContext();await second.route('https://**',r=>r.abort());const other=await second.newPage();await login(other);await other.locator('[data-page="catalogue"]').click();await other.locator('[data-detail="'+saved.id+'"]').click();assert((await other.locator('.specgrid').innerText()).includes('F05.412'));assert.deepEqual(errors,[]);
  console.log('PASS — vraie fiche Certina : 12 caractéristiques, référence/photo exactes, verre multiple, unités, recommandations/infobulles exclues, champs absents et marchés, aperçu/formulaire/sauvegarde/second navigateur, IA facultative et prix protégé.');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));await new Promise(r=>provider.close(r));await fs.rm(dir,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1});
