const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const {chromium}=require('playwright');const {createServer,validate}=require('../server.cjs');
(async()=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'watch-management-'));const server=createServer({password:'management-test',dataDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let browser;
 try{
  browser=await chromium.launch({executablePath:'/usr/bin/chromium'});const a=await browser.newContext();await a.route('https://**',r=>r.abort());const p=await a.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
  const ready=page=>page.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('à jour'));
  async function login(page){await page.goto(base);await page.locator('[data-connect]').first().click();await page.locator('#sharedPassword').fill('management-test');await page.locator('#loginButton').click();await ready(page)}
  const disk=async()=>JSON.parse(await fs.readFile(path.join(dir,'collection.json'),'utf8')).collection;
  async function watch(page){await page.locator('[data-page="catalogue"]').click();await page.locator('[data-detail="watch-35"]').click()}
  await login(p);const before=(await disk()).watches.find(w=>w.id==='watch-35');await watch(p);await p.locator('#note').fill('Mes notes à conserver');await ready(p);await p.locator('#editWatch').click();await p.locator('#watchStatus').selectOption('owned');
  await p.locator('#variantRows').evaluate(el=>el.closest('details').open=true);await p.locator('#addVariant').click();await p.locator('.variant-name').fill('Bleu arctique');await p.locator('.variant-ref').fill('CONC-BLUE');await p.locator('.variant-color').fill('Bleu');await p.locator('.variant-photo').selectOption('0');await p.locator('.variant-url').fill('https://example.org/blue');
  await p.locator('#linkRows').evaluate(el=>el.closest('details').open=true);await p.locator('.link-label').first().fill('Constructeur vérifié');await p.locator('.link-url').first().fill('https://example.org/model');
  await p.locator('#blockRows').evaluate(el=>el.closest('details').open=true);await p.locator('.block-title').first().fill('Avis personnel');await p.locator('.block-text').first().fill('Très agréable au poignet.');await p.locator('#watchForm [type="submit"]').click();await ready(p);
  let w=(await disk()).watches.find(w=>w.id==='watch-35');assert.equal(w.status,'owned');assert.equal(w.notes,'Mes notes à conserver');assert.equal(w.images[0].src,before.images[0].src);assert.equal(w.variants[0].reference,'CONC-BLUE');assert.equal(w.links[0].url,'https://example.org/model');assert.equal(w.blocks[0].text,'Très agréable au poignet.');assert.ok((await disk()).chosen.includes(w.id));
  await p.locator('[data-variant="0"]').click();assert.ok((await p.locator('#variantInfo').innerText()).includes('CONC-BLUE'));assert.equal(await p.locator('#variantInfo a').getAttribute('target'),'_blank');
  // An old open client may not erase metadata it does not know about.
  const remoteRecord=await(await a.request.get(base+'/api/collection')).json();const stale=structuredClone(remoteRecord);for(const x of stale.collection.watches){delete x.status;delete x.archived;delete x.variants}const denied=await a.request.put(base+'/api/collection',{data:stale});assert.equal(denied.status(),426);assert.equal((await disk()).watches.find(w=>w.id==='watch-35').status,'owned');
  // Replacing the main photo preserves the original linked to a colour variant.
  await p.locator('#editWatch').click();await p.locator('#imageDetails').evaluate(el=>el.open=true);await p.locator('#photoUrl').fill('https://example.org/other-color.png');await p.locator('#watchForm [type="submit"]').click();await ready(p);
  w=(await disk()).watches.find(w=>w.id==='watch-35');assert.equal(w.images[w.variants[0].photoIndex].src,before.images[0].src);assert.equal(w.images[0].src,'https://example.org/other-color.png');
  // Cancelled editor changes and cancelled archive do not mutate the record.
  await p.locator('#editWatch').click();await p.locator('#watchStatus').selectOption('rejected');await p.locator('#cancelEdit').click();assert.equal((await disk()).watches.find(w=>w.id==='watch-35').status,'owned');
  p.once('dialog',d=>d.dismiss());await p.locator('#archiveWatch').click();assert.equal((await disk()).watches.find(w=>w.id==='watch-35').archived,false);
  p.once('dialog',d=>d.accept());await p.locator('#archiveWatch').click();await ready(p);w=(await disk()).watches.find(w=>w.id==='watch-35');assert.equal(w.archived,true);assert.ok(!(await disk()).chosen.includes(w.id));assert.equal(w.notes,'Mes notes à conserver');
  await p.locator('[data-page="catalogue"]').click();assert.equal(await p.locator('tbody tr').count(),40);await p.locator('#lifecycle').selectOption('archived');assert.equal(await p.locator('tbody tr').count(),1);await p.locator('[data-detail="watch-35"]').click();await p.locator('#archiveWatch').click();await ready(p);assert.equal((await disk()).watches.find(w=>w.id==='watch-35').archived,false);
  await p.locator('#editWatch').click();await p.locator('#watchStatus').selectOption('rejected');await p.locator('#watchForm [type="submit"]').click();await ready(p);assert.equal((await disk()).watches.find(w=>w.id==='watch-35').status,'rejected');await p.locator('[data-page="collection"]').click();assert.equal(await p.locator('.card [data-detail="watch-35"]').count(),0);
  const b=await browser.newContext();await b.route('https://**',r=>r.abort());const q=await b.newPage();await login(q);await q.locator('[data-page="catalogue"]').click();await q.locator('#lifecycle').selectOption('rejected');await q.locator('[data-detail="watch-35"]').click();assert.equal(await q.locator('[data-variant="0"]').count(),1);assert.ok((await q.locator('.detail').first().innerText()).includes('Écartée'));
  const dl=await Promise.all([q.waitForEvent('download'),q.locator('[data-export]').click()]).then(v=>v[0]);const saved=JSON.parse(await fs.readFile(await dl.path(),'utf8'));assert.equal(saved.watches.find(w=>w.id==='watch-35').variants[0].name,'Bleu arctique');
  q.once('dialog',d=>d.dismiss());await q.locator('#deleteWatch').click();assert.equal((await disk()).watches.length,41);q.once('dialog',d=>d.accept());await q.locator('#deleteWatch').click();await ready(q);assert.equal((await disk()).watches.length,40);assert.ok(!(await disk()).watches.some(w=>w.id==='watch-35'));
  await q.locator('#importFile').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});await q.locator('#confirmImport').click();await ready(q);assert.equal((await disk()).watches.length,41);assert.equal((await disk()).watches.find(w=>w.id==='watch-35').variants[0].reference,'CONC-BLUE');
  const invalid=structuredClone(saved);invalid.watches[0].variants=[{name:'Test',photoIndex:999}];assert.throws(()=>validate(invalid));const old=structuredClone(saved);for(const w of old.watches){delete w.status;delete w.archived;delete w.variants}assert.equal(validate(old).watches[0].status,'wanted');
  assert.deepEqual(errors,[]);console.log('PASS — gestion : statuts, variantes/photo, sources/avis, notes préservées, annulation, archives/restauration, choix retirés, suppression/restauration JSON et second navigateur.');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));await fs.rm(dir,{recursive:true,force:true})}
})().catch(e=>{console.error(e);process.exitCode=1});
