const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const {chromium}=require('playwright');const {createServer,publicAddress,imageType}=require('../server.cjs');
(async()=>{
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
 assert.equal(imageType(png),'png');assert.throws(()=>imageType(Buffer.from('<html>')));for(const ip of ['127.0.0.1','10.0.0.1','192.168.1.1','169.254.169.254','::1','::ffff:127.0.0.1','fc00::1'])assert.equal(publicAddress(ip),false);
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'watch-photos-'));const source='https://example.org/exact-model.png';let calls=0;
 const server=createServer({password:'photo-test',dataDir:dir,photoDownloader:async url=>{calls++;if(url.includes('failure'))throw Error('Source indisponible');return{src:'data:image/png;base64,'+png.toString('base64'),sourceUrl:url}}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let browser;
 try{
  assert.equal((await fetch(base+'/api/photo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:source})})).status,401);
  browser=await chromium.launch({executablePath:'/usr/bin/chromium'});const c=await browser.newContext();await c.route('https://**',r=>r.abort());const p=await c.newPage();await p.goto(base);await p.locator('[data-connect]').first().click();await p.locator('#sharedPassword').fill('photo-test');await p.locator('#loginButton').click();await p.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('à jour'));
  await p.locator('[data-page="catalogue"]').click();await p.locator('[data-detail="watch-38"]').click();await p.locator('[data-cache-watch]').click();await p.waitForFunction(()=>document.querySelector('#photoProgress').textContent.includes('photo(s) copiée(s)'));assert.ok(calls>0);
  let record=JSON.parse(await fs.readFile(path.join(dir,'collection.json'),'utf8'));const image=record.collection.watches.find(w=>w.id==='watch-38').images[0];assert.ok(image.src.startsWith('data:image/png;base64,'));assert.ok(image.sourceUrl.startsWith('https://'));assert.equal(image.src.split(',')[1],png.toString('base64'));
  await p.locator('#closePhotos').click();await p.reload();await p.locator('[data-page="catalogue"]').click();await p.locator('[data-detail="watch-38"]').click();await p.waitForFunction(()=>document.querySelector('.detail .media img').naturalWidth===1);
  // A local file replaces the primary photo and preserves its previous original.
  await p.locator('#photoUpload').evaluate(el=>el.dataset.watch='watch-38');await p.locator('#photoUpload').setInputFiles({name:'photo.png',mimeType:'image/png',buffer:png});await p.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('à jour'));await p.waitForFunction(()=>document.querySelector('.photo-provenance').textContent.includes('intégrée'));
  const download=await Promise.all([p.waitForEvent('download'),p.locator('[data-export]').click()]).then(x=>x[0]);const exported=JSON.parse(await fs.readFile(await download.path(),'utf8'));assert.ok(exported.watches.find(w=>w.id==='watch-38').images[0].src.startsWith('data:'));
  await p.locator('#photoUpload').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('not a real photo')});await p.waitForFunction(()=>document.querySelector('#toast').textContent.includes('décodée'));assert.equal(JSON.parse(await fs.readFile(path.join(dir,'collection.json'),'utf8')).collection.watches.find(w=>w.id==='watch-38').images[0].src,image.src);
  const second=await browser.newContext();await second.route('https://**',r=>r.abort());const b=await second.newPage();await b.goto(base);await b.locator('[data-connect]').first().click();await b.locator('#sharedPassword').fill('photo-test');await b.locator('#loginButton').click();await b.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('à jour'));await b.locator('[data-page="catalogue"]').click();await b.locator('[data-detail="watch-38"]').click();await b.waitForFunction(()=>document.querySelector('.detail .media img').naturalWidth===1);
  console.log('PASS — photos : copie sur serveur, pixels conservés, provenance, rechargement sans site tiers, fichier local, export, image invalide refusée et second navigateur.');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));await fs.rm(dir,{recursive:true,force:true})}
})().catch(e=>{console.error(e);process.exitCode=1});
