const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const {chromium}=require('playwright');const {createServer}=require('../server.cjs');
(async()=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'watch-photo-limits-')),password='photo-limits-test',server=createServer({password,dataDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let browser;
 try{
  browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium'});const a=await browser.newContext();await a.route('https://**',r=>r.abort());const p=await a.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
  const ready=page=>page.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('à jour'),null,{timeout:60000});
  async function login(page){await page.goto(base);await page.locator('[data-connect]').first().click();await page.locator('#sharedPassword').fill(password);await page.locator('#loginButton').click();await ready(page);}
  const disk=async()=>JSON.parse(await fs.readFile(path.join(dir,'collection.json'),'utf8'));
  await login(p);
  // Upgrade from the old localStorage draft without losing pending notes.
  await p.evaluate(async()=>{await draftWrites;const legacy={revision:remote.revision,pending:true,collection:clone(state)};legacy.collection.watches.find(w=>w.id==='watch-35').notes='Ancien brouillon local';const db=await draftDB();await new Promise((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').delete(REMOTE_CACHE_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});localStorage.setItem(REMOTE_CACHE_KEY,JSON.stringify(legacy));});
  await p.reload();await ready(p);assert.equal(await p.evaluate(()=>state.watches.find(w=>w.id==='watch-35').notes),'Ancien brouillon local');assert.equal(await p.evaluate(()=>localStorage.getItem(REMOTE_CACHE_KEY)),null);

  // Actual decodable, incompressible photographs put the collection past both
  // former limits. Applying a photo exercises the old 28 MB rejection point.
  const largeSize=await p.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;const ctx=canvas.getContext('2d'),pixels=ctx.createImageData(512,512);let random=12345;for(let i=0;i<pixels.data.length;i+=4){for(let c=0;c<3;c++){random^=random<<13;random^=random>>>17;random^=random<<5;pixels.data[i+c]=random&255;}pixels.data[i+3]=255;}ctx.putImageData(pixels,0,0);const src=canvas.toDataURL('image/png');for(const w of state.watches)w.images=[{src,cutoutSrc:'',alt:w.name,fallbacks:[],transparent:false}];applyPhoto(byId('watch-35'),0,{...byId('watch-35').images[0]});return new TextEncoder().encode(JSON.stringify(state)).length;});
  assert(largeSize>30000000&&largeSize<100000000);await ready(p);let record=await disk();assert.equal(record.collection.watches.length,41);assert.equal(Buffer.byteLength(JSON.stringify(record.collection)),largeSize);
  await p.evaluate(()=>draftWrites);assert.equal(await p.evaluate(async()=>{const draft=await cachedRemote();return draft.pending;}),false);assert.equal(await p.evaluate(()=>localStorage.getItem(REMOTE_CACHE_KEY)),null);
  const b=await browser.newContext();await b.route('https://**',r=>r.abort());const q=await b.newPage();await login(q);assert.equal(await q.evaluate(()=>state.watches[0].images[0].src.length),record.collection.watches[0].images[0].src.length);
  // A large pending draft survives a network failure and reload even though it
  // cannot fit localStorage; another browser sees it only after server ack.
  await p.locator('.collection-photo[data-detail="watch-35"]').click();await p.route('**/api/collection',r=>r.abort());await p.locator('#note').fill('Brouillon de plus de 30 Mo');await p.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('Non synchronisé'));await p.evaluate(()=>draftWrites);assert.equal(await p.evaluate(async()=>(await cachedRemote()).pending),true);
  p.once('dialog',d=>d.accept());await p.reload();await p.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('Non synchronisé'));await p.locator('.collection-photo[data-detail="watch-35"]').click();assert.equal(await p.locator('#note').inputValue(),'Brouillon de plus de 30 Mo');await p.unroute('**/api/collection');await p.locator('[data-retry]').click();await ready(p);await q.locator('[data-refresh]').click();await q.waitForFunction(()=>state.watches.find(w=>w.id==='watch-35').notes==='Brouillon de plus de 30 Mo');await q.locator('.collection-photo[data-detail="watch-35"]').click();assert.equal(await q.locator('#note').inputValue(),'Brouillon de plus de 30 Mo');
  const download=await Promise.all([p.waitForEvent('download'),p.locator('[data-export]').first().click()]).then(r=>r[0]);const exported=await fs.readFile(await download.path());assert(exported.length>30000000);await p.locator('#importFile').setInputFiles({name:'large.json',mimeType:'application/json',buffer:exported});await p.locator('#importDialog').waitFor({state:'visible'});await p.locator('#cancelImport').click();
  // Over-limit insertion is rolled back, leaving the server record untouched.
  assert.equal(await p.evaluate(()=>{const w=byId('watch-35'),before=JSON.stringify(w);try{const big='data:image/png;base64,'+'A'.repeat(80000000);applyPhoto(w,0,{src:big,cutoutSrc:'',alt:'Too large',fallbacks:[]},true);return false;}catch(e){return e.message.includes('100 Mo')&&JSON.stringify(w)===before;}}),true);
  const loginResponse=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}),headers={'Content-Type':'application/json',Cookie:loginResponse.headers.get('set-cookie').split(';')[0]};
  record=await disk();const image=record.collection.watches[0].images[0],imageCount=Math.ceil(100100000/JSON.stringify(image).length),tooLarge={version:1,watches:[{...record.collection.watches[0],images:Array(imageCount).fill(image)}],chosen:Array(8).fill(null)},request=JSON.stringify({revision:record.revision,collection:tooLarge});assert(Buffer.byteLength(request)>100000000&&Buffer.byteLength(request)<102000000);const refusal=await fetch(base+'/api/collection',{method:'PUT',headers,body:request});assert.equal(refusal.status,413);assert((await refusal.json()).error.includes('100 Mo'));assert.equal((await disk()).revision,record.revision);
  assert.deepEqual(errors,[]);console.log('PASS — carnet de '+Math.round(largeSize/1000000)+' Mo : ajout, sauvegarde serveur, second navigateur, brouillon IndexedDB hors ligne/rechargement/reprise, export/import >30 Mo et refus avec retour arrière au-delà de 100 Mo.');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));await fs.rm(dir,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
