const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const {chromium}=require('playwright');const {createServer,validate}=require('../server.cjs');
(async()=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'watch-visuals-'));let remoteFixture='';const downloadedSources=[];const server=createServer({password:'visual-test',dataDir:dir,photoDownloader:async url=>{downloadedSources.push(url);if(url.endsWith('/missing.png'))throw Error('Photo indisponible');return{src:remoteFixture,sourceUrl:url}}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let browser;
 try{
  browser=await chromium.launch({executablePath:'/usr/bin/chromium'});const a=await browser.newContext({viewport:{width:1280,height:1050}});await a.route('https://**',r=>r.abort());const p=await a.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
  const ready=page=>page.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('à jour'));
  async function login(page){await page.goto(base);await page.locator('[data-connect]').first().click();await page.locator('#sharedPassword').fill('visual-test');await page.locator('#loginButton').click();await ready(page);}
  const disk=async()=>JSON.parse(await fs.readFile(path.join(dir,'collection.json'),'utf8'));
  await login(p);assert.equal(await p.evaluate(()=>document.documentElement.dataset.theme),'dark');
  assert((await p.locator('link[rel="icon"][type="image/svg+xml"]').getAttribute('href')).startsWith('data:image/svg+xml,'));assert.equal(await p.evaluate(()=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve(i.naturalWidth);i.onerror=()=>resolve(0);i.src=document.querySelector('link[rel="icon"][type="image/svg+xml"]').href;})),64);
  const initialRevision=(await disk()).revision;await p.locator('#themeToggle').click();assert.equal(await p.evaluate(()=>document.documentElement.dataset.theme),'light');assert.equal(await p.locator('#themeToggle').textContent(),'Mode sombre');await p.reload();await ready(p);assert.equal(await p.evaluate(()=>document.documentElement.dataset.theme),'light');assert.equal((await disk()).revision,initialRevision);
  const samples=await p.evaluate(()=>{function create(background){const canvas=document.createElement('canvas');canvas.width=120;canvas.height=160;const c=canvas.getContext('2d');if(background){c.fillStyle=background;c.fillRect(0,0,120,160);}c.fillStyle='#303030';c.fillRect(35,20,50,120);c.fillStyle='#ffffff';c.fillRect(42,55,36,45);c.fillStyle='#2266aa';c.fillRect(54,65,5,20);return canvas.toDataURL('image/png');}return{white:create('#ffffff'),dark:create('#202020'),transparent:create(null)};});
  remoteFixture=samples.white;
  // Real pixel assertions: connected white background disappears, an enclosed
  // white dial stays opaque, and blue details retain their original RGB values.
  const result=await p.evaluate(async src=>{const r=await removePlainBackground(src);const im=await loadPhotoElement(r.src),canvas=document.createElement('canvas');canvas.width=im.naturalWidth;canvas.height=im.naturalHeight;const c=canvas.getContext('2d');c.drawImage(im,0,0);const d=c.getImageData(0,0,canvas.width,canvas.height).data;let blue=0,opaqueWhite=0;for(let i=0;i<d.length;i+=4){if(d[i]===34&&d[i+1]===102&&d[i+2]===170&&d[i+3]===255)blue++;if(d[i]===255&&d[i+1]===255&&d[i+2]===255&&d[i+3]===255)opaqueWhite++;}return{...r,cornerAlpha:d[3],blue,opaqueWhite};},samples.white);
  assert.equal(result.cornerAlpha,0);assert.equal(result.blue,100);assert.equal(result.opaqueWhite,36*45-100);assert(result.width<120);assert(result.height<160);
  assert.equal(await p.evaluate(async src=>(await removePlainBackground(src)).alreadyTransparent,samples.transparent),true);
  assert(await p.evaluate(async src=>{try{await removePlainBackground(src);return false}catch(e){return e.message.includes('clair et uni')}},samples.dark));
  let record=await(await a.request.get(base+'/api/collection')).json();const w=record.collection.watches.find(w=>w.id==='watch-35');w.images[0]={src:samples.white,cutoutSrc:'',alt:'Photo de test sur fond blanc',fallbacks:[],transparent:false};assert.equal((await a.request.put(base+'/api/collection',{data:record})).status(),200);await p.reload();await ready(p);await p.locator('.collection-photo[data-detail="watch-35"]').click();const before=await disk();await p.locator('[data-cutout-photo]').click();await p.locator('#applyCutout').waitFor({state:'visible'});await p.waitForFunction(()=>!document.querySelector('#applyCutout').disabled);assert.equal((await disk()).revision,before.revision);await p.locator('#cancelCutout').click();assert.equal((await disk()).revision,before.revision);
  await p.locator('[data-cutout-photo]').click();await p.waitForFunction(()=>!document.querySelector('#applyCutout').disabled);await p.locator('#applyCutout').click();await ready(p);let saved=(await disk()).collection.watches.find(w=>w.id==='watch-35').images[0];assert.equal(saved.src,samples.white);assert(saved.cutoutSrc.startsWith('data:image/png;base64,'));assert.equal(await p.locator('.detail .media img').getAttribute('src'),saved.cutoutSrc);assert(await p.locator('.detail .media').evaluate(el=>el.classList.contains('transparent')));
  const second=await browser.newContext();await second.route('https://**',r=>r.abort());const q=await second.newPage();await login(q);assert.equal(await q.locator('.collection-photo[data-detail="watch-35"] img').getAttribute('src'),saved.cutoutSrc);assert.equal(await q.evaluate(()=>document.documentElement.dataset.theme),'dark');
  const dl=await Promise.all([p.waitForEvent('download'),p.locator('[data-export]').click()]).then(x=>x[0]);const exported=JSON.parse(await fs.readFile(await dl.path(),'utf8'));const photo=exported.watches.find(w=>w.id==='watch-35').images[0];assert.equal(photo.src,samples.white);assert.equal(photo.cutoutSrc,saved.cutoutSrc);
  const htmlDownload=await Promise.all([p.waitForEvent('download'),p.locator('[data-html]').click()]).then(x=>x[0]);const html=await fs.readFile(await htmlDownload.path(),'utf8');const embedded=JSON.parse(html.match(/<script id="initialData" type="application\/json">([^]*?)<\/script>/)[1]);assert.equal(embedded.watches.find(w=>w.id==='watch-35').images[0].cutoutSrc,saved.cutoutSrc);assert(html.includes('data:image/svg+xml,'));
  const staticServer=createServer({htmlPath:await htmlDownload.path(),dataDir:path.join(dir,'standalone')});await new Promise(r=>staticServer.listen(0,'127.0.0.1',r));try{const standalone=await browser.newContext();await standalone.route('https://**',r=>r.abort());const sp=await standalone.newPage();await sp.goto('http://127.0.0.1:'+staticServer.address().port);await sp.locator('.collection-photo[data-detail="watch-35"] img').waitFor();assert.equal(await sp.locator('.collection-photo[data-detail="watch-35"] img').getAttribute('src'),saved.cutoutSrc);await standalone.close();}finally{await new Promise(r=>staticServer.close(r));}

  // A remote gallery photo uses the fallback source, keeps the downloaded
  // original only after approval, and stays selected in the detail preview.
  record=await(await a.request.get(base+'/api/collection')).json();const remoteWatch=record.collection.watches.find(w=>w.id==='watch-35'),galleryIndex=remoteWatch.images.length;remoteWatch.images.push({src:'https://example.org/missing.png',cutoutSrc:'',alt:'Photo distante',fallbacks:['https://example.org/available.png'],transparent:false});assert.equal((await a.request.put(base+'/api/collection',{data:record})).status(),200);await p.reload();await ready(p);await p.locator('.collection-photo[data-detail="watch-35"]').click();await p.locator('button[data-image="'+galleryIndex+'"]').click();await p.locator('[data-cutout-photo]').click();await p.waitForFunction(()=>!document.querySelector('#applyCutout').disabled);assert.equal((await disk()).collection.watches.find(w=>w.id==='watch-35').images[galleryIndex].src,'https://example.org/missing.png');await p.locator('#applyCutout').click();await ready(p);const copied=(await disk()).collection.watches.find(w=>w.id==='watch-35');assert.equal(copied.images[galleryIndex].src,samples.white);assert.equal(copied.images[galleryIndex].sourceUrl,'https://example.org/available.png');assert(copied.images[galleryIndex].cutoutSrc);assert.equal(copied.defaultPhoto,null);assert.equal(await p.locator('.detail .media img').getAttribute('data-image'),String(galleryIndex));assert.deepEqual(downloadedSources,['https://example.org/missing.png','https://example.org/available.png']);
  record=await(await a.request.get(base+'/api/collection')).json();const stale=structuredClone(record);for(const watch of stale.collection.watches)for(const image of watch.images)delete image.cutoutSrc;assert.equal((await a.request.put(base+'/api/collection',{data:stale})).status(),426);assert.equal(validate(stale.collection).watches[0].images[0].cutoutSrc,'');
  const invalid=structuredClone(record.collection);invalid.watches[0].images[0].cutoutSrc='https://example.org/fake.png';assert.throws(()=>validate(invalid));
  // Captured light UI and editor for manual visual review.
  await p.locator('#back').click();await p.screenshot({path:'/tmp/watch-light-collection.png'});await p.locator('#add').click();await p.screenshot({path:'/tmp/watch-light-editor.png'});await p.locator('#cancelEdit').click();await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await p.locator('.collection-photo[data-detail="watch-35"]').click();await p.locator('[data-undo-cutout]').click();await ready(p);saved=(await disk()).collection.watches.find(w=>w.id==='watch-35').images[0];assert.equal(saved.cutoutSrc,'');assert.equal(saved.src,samples.white);assert.equal(await p.locator('.detail .media img').getAttribute('src'),samples.white);
  await p.locator('#themeToggle').click();assert.equal(await p.evaluate(()=>document.documentElement.dataset.theme),'dark');assert.deepEqual(errors,[]);
  // Real manufacturer photo: the soft floor shadow disappears while the
  // pale dial, brown leather and crown remain part of the foreground mask.
  const charlie='data:image/jpeg;base64,'+(await fs.readFile(path.join(__dirname,'fixtures/charlie-slim.jpg'))).toString('base64');
  const actual=await p.evaluate(async src=>{const image=await loadPhotoElement(src),canvas=document.createElement('canvas');canvas.width=1000;canvas.height=1000;const c=canvas.getContext('2d');c.drawImage(image,0,0,1000,1000);const pixels=c.getImageData(0,0,1000,1000).data,mask=contourSubject(pixels,1000,1000,24);const r=await removePlainBackground(src,{mode:'contours',threshold:24});return{dial:mask[450*1000+500],strap:mask[150*1000+500],crown:mask[460*1000+760],shadow:mask[965*1000+500],corner:mask[0],width:r.width,height:r.height,bytes:r.src.length};},charlie);
  assert.equal(actual.dial,1);assert.equal(actual.strap,1);assert.equal(actual.crown,1);assert.equal(actual.shadow,0);assert.equal(actual.corner,0);assert(actual.width<650&&actual.width>500);assert(actual.height<1000&&actual.height>900);
  record=await(await a.request.get(base+'/api/collection')).json();record.collection.watches.find(w=>w.id==='watch-35').images[0]={src:charlie,cutoutSrc:'',alt:'Charlie Paris Initial Slim — Blanc',fallbacks:[],transparent:false};assert.equal((await a.request.put(base+'/api/collection',{data:record})).status(),200);await p.setViewportSize({width:1280,height:1050});await p.reload();await ready(p);await p.locator('.collection-photo[data-detail="watch-35"]').click();await p.locator('[data-cutout-photo]').click();await p.waitForFunction(()=>!document.querySelector('#applyCutout').disabled);assert.equal(await p.locator('#cutoutMethod').inputValue(),'contours');const revisionBeforePreview=(await disk()).revision;
  await p.locator('#cutoutMethod').selectOption('plain');await p.waitForFunction(()=>!document.querySelector('#applyCutout').disabled);assert.equal(await p.locator('#cutoutStrengthLabel').isVisible(),false);const plainPreview=await p.locator('#cutoutAfter').getAttribute('src');await p.locator('#cutoutMethod').selectOption('contours');await p.waitForFunction(()=>!document.querySelector('#applyCutout').disabled);assert.notEqual(await p.locator('#cutoutAfter').getAttribute('src'),plainPreview);
  await p.locator('#cutoutStrength').fill('16');await p.locator('#cutoutStrength').dispatchEvent('change');await p.waitForFunction(()=>!document.querySelector('#applyCutout').disabled);const softer=await p.locator('#cutoutAfter').getAttribute('src');await p.locator('#cutoutStrength').fill('24');await p.locator('#cutoutStrength').dispatchEvent('change');await p.waitForFunction(()=>!document.querySelector('#applyCutout').disabled);assert.notEqual(await p.locator('#cutoutAfter').getAttribute('src'),softer);assert.equal((await disk()).revision,revisionBeforePreview);
  await p.locator('#cutoutDialog').screenshot({path:'/tmp/watch-charlie-cutout.png'});await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#applyCutout').click();await ready(p);assert.equal((await disk()).collection.watches.find(w=>w.id==='watch-35').images[0].src,charlie);assert.deepEqual(errors,[]);
  console.log('PASS — présentation : favicon décodable, thème clair/sombre mémorisé et mobile, détourage/pixels préservés, fond complexe refusé, transparent recadré, vraie Charlie Slim/ombres et réglages, aperçu/annulation, original et retour, second navigateur, export et ancienne page protégée.');
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));await fs.rm(dir,{recursive:true,force:true})}
})().catch(e=>{console.error(e);process.exitCode=1});
